<?php
$attributecollection = Mage::getModel('measurement/attribute')->getCollection();//->getData();
$setId = $this->getRequest()->getParam('id');

$setValueCollection = Mage::getModel('measurement/attributesetvalue')
        ->getCollection()
        ->addFieldToFilter('attribute_set_id', $setId);
        //->getData();
/*
 echo "<pre>";
  print_r($setValueCollection);
  print_r($attributecollection);
  echo "</pre>"; */
?>


<div class="entity-edit" id="matage-options-panel">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('measurement')->__("Select Attributes for '%s'",$this->htmlEscape(Mage::registry('category_data')->getTitle()))?></h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table class="dynamic-grid" cellspacing="0"  cellpadding="0">	
<tr class="">
                        <th class="">&nbsp;</th>
                        <th class="">Attribute</th>
                        <th class="">Sort Order</th>
                    </tr>
                <?php
                foreach ($attributecollection as $attribute) {
                    $checked = NULL;
                     $sortOrder = $attribute->getSortOrder();
                    foreach ($setValueCollection as $value)
                    {
                       if($value->getAttributeId() == $attribute->getId())
                        {
                            $checked = 'checked';
                            $sortOrder = $value->getSortOrder();
                            //$setValueDetail = Mage::getModel('measurement/attributesetvalue')->load($attribute->getId());
                            //$sortOrder = $setValueDetail->getSortOrder();die;
                            break;
                        }
                            
                    }
                    
                    ?>
                    <tr class="">
                        <td class=""><input <?php echo $checked ?> type="checkbox" name="chkAttribute[<?php echo $setId ?>][]" id="chkAttribute[<?php echo $setId ?>][]" value="<?php echo $attribute->getId();//['attribute_id'] ?>"></td>
                        <td class=""><?php echo $attribute->getTitle()?></td>
                        <td class=""><input type="text" name="txtSortOrder[<?php echo $setId ?>][]" id="txtSortOrder[<?php echo $setId ?>][]" value="<?php echo ($sortOrder) ? $sortOrder : 0;//$attribute->getSortOrder()?>"></td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>

<style>
    .dynamic-grid td{
     padding-right: 10px;   
    }
    
</style>