<?php
$collection = Mage::getModel('measurement/soptions')->getCollection()
        ->addFieldToFilter('attribute_id', $this->getRequest()->getParam('id'));
$Optioncollection = $collection->getData();
?>
<div class="entity-edit" style="display:none">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Manage Titles (Size, Color, etc.)</h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table cellspacing="0" id="attribute-labels-table" class="dynamic-grid">
                <tbody><tr>
                        <th>Title</th>
                      

                    </tr>
                    <tr>
                        <td>
                            <input type="text" value="" name="title2" class="input-text required-option">
                        </td>
                       

                    </tr>
                </tbody></table>
        </div>
    </div>
</div>

<div class="entity-edit" id="matage-options-panel">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__('Manage Options (values of your attribute)') ?></h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table class="dynamic-grid" cellspacing="0"  cellpadding="0">	
                <tr id="attribute-options-table">
                    <td>
                        <button id="add_new_option_button" name="remove" class="scalable add" style="" onclick="addRow('control_container');" type="button" title="Add Option">
                            <span><span><?php echo $this->__('Add Option'); ?></span></span>
                        </button>
                        &nbsp;
                        <button  class="scalable delete delete-option" onclick="deleteRow('control_container');" type="button" title="Delete"><span><span><span>Delete</span></span></span></button>
                    </td> 
                </tr>

                <tr>
                    <td>
                        <table id="control_container" width="60%">
                            <tr>
                                <th>Remove</th>
                                <th>Title</th>					
                                <th>Sort Order</th>
                                <th>Image</th>
                            </tr>
                            <?php $ids = ''; ?>
                            <?php for ($i = 0; $i < count($Optioncollection); $i++) {
//							echo "<pre>";
	//						print_r( $Optioncollection[$i]);
							 ?>
                                <?php $ids = $Optioncollection[$i]['style_option_id'] . ',' . $ids; ?>
                                <tr>
                                    <td><input type="checkbox" value="<?php echo $Optioncollection[$i]['option_id']; ?>" name="chkbox[]"></td>
                                    <td><input type="text" class="required-entry input-text" name="option_title[]"  value="<?php echo $Optioncollection[$i]['title']; ?>"></td>
                                    <td><input type="text" name="option_sort_order[]" value="<?php echo $Optioncollection[$i]['sort_order']; ?>"></td>
                                    <td><input type="file" name="option_image[]" ><input type="hidden" value="<?php echo $Optioncollection[$i]['option_id']; ?>" name="hdnId[]"></td>

                                </tr>
                            <?php } ?>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<input type='hidden' id='hdnDeleteIds' name='hdnDeleteIds' value='null'>

<script>
                            function addRow(tableID) {

                                var table = document.getElementById(tableID);

                                var rowCount = table.rows.length;
                                var row = table.insertRow(rowCount);

                                var cell1 = row.insertCell(0);
                                var element1 = document.createElement("input");
                                element1.type = "checkbox";
                                element1.name = "chkbox[]";

                                cell1.appendChild(element1);

                                var cell2 = row.insertCell(1);
                                var element2 = document.createElement("input");
                                element2.type = "text";
                                element2.name = "option_title[]";
                                element2.class = "test";
                                cell2.appendChild(element2);

                                var cell3 = row.insertCell(2);
                                var element3 = document.createElement("input");
                                element3.type = "text";
                                element3.name = "option_sort_order[]";
                                cell3.appendChild(element3);

                                var cell4 = row.insertCell(3);
                                var element4 = document.createElement("input");
                                element4.type = "file";
                                element4.name = "option_image[]";
                                cell4.appendChild(element4);
                            }

                            function deleteRow(tableID) {
                                try {
                                    var ids = 0;
                                    var table = document.getElementById(tableID);
                                    var rowCount = table.rows.length;

                                    for (var i = 0; i < rowCount; i++) {
                                        var row = table.rows[i];
                                        var chkbox = row.cells[0].childNodes[0];
                                        if (null != chkbox && true == chkbox.checked) {
                                            table.deleteRow(i);
                                            rowCount--;
                                            i--;
                                            ids = ids + ',' + chkbox.value;

                                        }
                                    }
                                    $('hdnDeleteIds').value = ids;
                                } catch (e) {
                                    alert(e);
                                }
                            }
                            /*
                             $('#manage-options-panel').hide();
                             
                             $('#answer_input_type').change(function() {
                             
                             if($(this).find("option:selected").val() == "select") {
                             
                             $('#manage-options-panel').show();
                             
                             
                             
                             }
                             });
                             **/

                            function checkOptionsPanelVisibility() {
                                if ($('matage-options-panel')) {
                                    var panel = $('matage-options-panel');
                                    if ($('frontend_input') && ($('frontend_input').value == 'select' || $('frontend_input').value == 'multiselect')) {
                                        panel.show();
                                    }
                                    else {
                                        panel.hide();
                                    }
                                }
                            }

                            if ($('frontend_input')) {
                                Event.observe($('frontend_input'), 'change', checkOptionsPanelVisibility);
                                //Event.observe($('frontend_input'), 'change', bindAttributeInputType);
                                //Event.observe($('is_global'), 'change', checkIsConfigurableVisibility);
                            }
                            checkOptionsPanelVisibility();
</script>

<style>
    .shop-locator .dynamic-grid td input{
        width: 200px;
    }
    .shop-locator .shop-img-label{
        text-align: left !important;
    }
</style>